name: Unit Tests

on:
  push:
    paths:
      - 'lib/**/*.js'
      - '__tests__/**/*.js'
      - 'package.json'
      - '.github/workflows/test.yml'
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [v16.x, v18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: mskelton/setup-yarn@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
